# Generated by Django 2.2.1 on 2019-05-09 01:28
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="post", name="content", field=models.TextField(default="")
        )
    ]
