# Generated by Django 2.2.1 on 2019-05-11 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("posts", "0008_remove_post_content_html")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=uuid.uuid1, unique=True),
        )
    ]
