# Generated by Django 2.2.1 on 2019-05-11 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
