# Generated by Django 2.2.1 on 2019-06-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190607_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_author',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='cover image author'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_caption',
            field=models.CharField(default='Photo', max_length=200, verbose_name='cover image caption'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_source',
            field=models.CharField(default='', max_length=1000, verbose_name='cover image source'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='post title'),
        ),
    ]
