# Generated by Django 2.2.1 on 2019-06-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190607_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_author',
            field=models.CharField(blank=True, default='Unknown', max_length=200, verbose_name='cover image author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_caption',
            field=models.CharField(blank=True, default='Photo', max_length=200, verbose_name='cover image caption'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_source',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='cover image source'),
        ),
    ]
